### ISSUE TITLE
Issue 6 User can sort entry by date created

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/code-journal#11]
## 💰 Motivation

User should be able to view notes chronologically.

## 📐 Plan

Allow users to click a button to sort entries in the entry list by date added.

## ✅ Task List

- [ ] Add button on the entries list page ONLY on the entries list page
- [ ] Button will toggle sorting the entry list from newest to oldest
- [ ] Button will toggle sorting the entry list from oldest to newest
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
