### ISSUE TITLE
Issue 7 User can add tags to an entry

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/code-journal#13]
## 💰 Motivation

A user should be able to add tags to their posts for organizational/topical reasons

## 📐 Plan

Allow users to input tags for each entry on creation and when editing

## ✅ Task List

- [x] Create an additional input section in the form creation page to take tag names
- [x] Parse the inputs by commas
- [x] Assign inputs to the respective objects
- [x] Add a line in the entries list  that displays all tags that the entry has
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
