### ISSUE TITLE
Issue 8 User can filter entries by tag

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/code-journal#15]
## 💰 Motivation

Why have tags if you can't filter by tags!

## 📐 Plan

Allow users to filter by tags.

## ✅ Task List

- [x] Add eventListener for the anchor tags (or potential parent div for bubbling)
- [x] Read which tag was clicked
- [x] Filter and select entries with said tag
- [x] Show only entries that include the tag
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
