### ISSUE TITLE
Issue 5 User can search their entries

### ISSUE THREAD

**Issue by hsu-isaac** [16hsuisaac/code-journal#9]
## 💰 Motivation

If a user is searching for an entry, there should be a search feature to make their search easier.

## 📐 Plan

Allow users to search for an entry from the entries list screen.

## ✅ Task List
 - [x] Add a search bar that appears only in the entries list
 - [x] Select entries that do not have matching terms in the title
 - [x] Hide those entries in the entries list
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x] Test all functionality again in a private browsing session.
 - [x] Fix all errors.
